### ISSUE TITLE
Add support for version 8.5.

### ISSUE THREAD

**Issue by chaitali-123** [chamilad/kibana-prometheus-exporter#21]

**Comment by chamilad** [comment]
Sorry, been busy a bit. Seeing this issue just now. I'll get a release out by the end of the month.

**Comment by chamilad** [comment]
@chaitali-123 sorry, I'm just getting around to this.

I tested the latest build off master with Kibana/Elasticsearch 8.5.3, and I can see all metrics from the API being passed through as open metrics format. Are you coming across any particular issue with 8.5?

**Comment by chaitali-123** [comment]
yes. kibana endpoint `/api/status` output is changed and kibana_Exporter metrics values are also not true.

**Comment by chamilad** [comment]
Can you let me know which metrics are wrong? Also, checkout the latest release matching version 8.5 to see if you're getting the expected output. I fixed the status change, but I'm going to need more information on the specific metrics you're observing as wrong.

**Comment by chaitali-123** [comment]
the `kibana_status` 0/1 value I am observing is wrong.  Instead of 1 it is showing 0.

**Comment by chamilad** [comment]
Can you double check you're using the newest release on your test? I just did a local test on 8.5.3 and I'm seeing the correct status
![image](https://user-images.githubusercontent.com/505989/233361974-47ff1972-976f-4ed8-821c-328b35dabf35.png)

**Comment by chaitali-123** [comment]
Thanks @chamilad  Upgraded to latest release and it is working. Thanks for quick response.
