### ISSUE TITLE
container create failed

### ISSUE THREAD

**Issue by AlbusLumos** [chamilad/kibana-prometheus-exporter#36]
Error: container create failed: time="2023-04-02T13:07:47+08:00" level=error msg="container_linux.go:380: starting container process caused: exec: \"/bin/kibana_exporter\": permission denied"

how can i fix this issue?

**Comment by chamilad** [comment]
Reproduced, but I couldn't check in depth. Probably a missing `chmod +x` in the build. I will check and fix this weekend.

**Comment by b2ronn** [comment]
/bin/kibana_exporter is a folder
but the binary doesn't have +x either
~ $ ls -lah /bin/ | grep kibana_expor
drwxr-xr-x    2 root     root          50 Apr 17 20:27 kibana_exporter
~ $ ls -lah /bin/kibana_exporter/
total 9M
drwxr-xr-x    2 root     root          50 Apr 17 20:27 .
drwxr-xr-x    1 root     root          29 Apr 17 20:27 ..
-rw-r--r--    1 root     root        8.5M Apr 17 20:27 kibana_exporter-v8.7.x.1-linux-amd64

**Comment by chamilad** [comment]
Sorry about the delay. This is now fixed in release `v8.7.x.2` - https://github.com/chamilad/kibana-prometheus-exporter/releases/tag/v8.7.x.2
