### ISSUE TITLE
Helm chart

### ISSUE THREAD

**Issue by pavdmyt** [chamilad/kibana-prometheus-exporter#4]
JFYI I've created a basic [helm chart](https://github.com/AnchorFree/helm-charts/tree/master/stable/kibana-exporter) to simplify deployments in Kubernetes. We're successfully using it. The installation is as simple as:

```
$ helm repo add afcharts https://anchorfree.github.io/helm-charts
$ helm repo update
$ helm install <release-name> afcharts/kibana-exporter
```

**Comment by chamilad** [comment]
Awesome! Thanks @pavdmyt ! I'm going to add a reference to this chart from the README. Nit: Is the Helm v3 version also available?

**Comment by pavdmyt** [comment]
It is Helm v2 chart (defined via `apiVersion: v1` in [Chart.yaml](https://github.com/AnchorFree/helm-charts/blob/master/stable/kibana-exporter/Chart.yaml)). We're using it in Helm v2 environment. However, I can make a new release with Helm v3 compatible `Chart.yaml`.
